apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: smart-parking
  namespace: argocd
spec:
  description: Smart Parking dev and prod GitOps environments.
  sourceRepos:
    - https://github.com/UST-Capstone-Project/Parking-System.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: dev
    - server: https://kubernetes.default.svc
      namespace: prod
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
