namespace: dev
environment: dev
authService:
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/auth-service
      tag: 1bad76870a39ac4c7c823ec4d9850b264e61b016
bookingService:
  configMap:
    data:
      APP_ENV: dev
      SQS_ENABLED: "true"
      NOTIFICATION_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/533595510771/smart-parking-dev-notifications
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/booking-service
      tag: f473ecc325cad6e9b4b78742a821a9e7a7d54ae9
frontend:
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/frontend
      tag: 54a1e08ee7d39a5398c0413d8ab8b95c8d03a69b
notificationService:
  configMap:
    data:
      APP_ENV: dev
      SQS_ENABLED: "true"
      NOTIFICATION_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/533595510771/smart-parking-dev-notifications
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/notification-service
      tag: 7bbf76024eee1fd8ee6580326a0411210218b600
parkingService:
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/parking-service
      tag: 2a925242d9e1069f2c8dca7c5ab3cfbf67a611f9
paymentService:
  configMap:
    data:
      APP_ENV: dev
      SQS_ENABLED: "true"
      NOTIFICATION_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/533595510771/smart-parking-dev-notifications
      INVOICE_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/533595510771/smart-parking-dev-invoices
      PAYMENT_INVOICE_BUCKET: smart-parking-dev-invoices-533595510771-us-east-1
      PAYMENT_INVOICE_KMS_KEY_ARN: arn:aws:kms:us-east-1:533595510771:alias/smart-parking-dev-invoices
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/payment-service
      tag: 57269ec163c00748f1c3a417fb3764c98a60f175
schedulerService:
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/scheduler-service
      tag: 91e855f81277ba612f6e6ce0f67ce2fbf5fb34aa
ingress:
  name: smart-parking-dev-alb
