namespace: dev
environment: dev
authService:
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/auth-service
      tag: f43154398d257f8913f54f12de959bb3c5160bc3
bookingService:
  configMap:
    data:
      APP_ENV: dev
      SQS_ENABLED: "true"
      NOTIFICATION_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/533595510771/smart-parking-dev-notifications
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/booking-service
      tag: c66b5b60afd004eb1f11b26983b65459352e3d21
frontend:
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/frontend
      tag: 54a1e08ee7d39a5398c0413d8ab8b95c8d03a69b
notificationService:
  configMap:
    data:
      APP_ENV: dev
      SQS_ENABLED: "true"
      NOTIFICATION_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/533595510771/smart-parking-dev-notifications
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/notification-service
      tag: 3acbff8bf0cf8924f499342329fde4737b223992
parkingService:
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/parking-service
      tag: 0ddca4239a21215f1eb67e41ee5a66452acdb63e
paymentService:
  configMap:
    data:
      APP_ENV: dev
      SQS_ENABLED: "true"
      NOTIFICATION_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/533595510771/smart-parking-dev-notifications
      INVOICE_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/533595510771/smart-parking-dev-invoices
      PAYMENT_INVOICE_BUCKET: smart-parking-dev-invoices-533595510771-us-east-1
      PAYMENT_INVOICE_KMS_KEY_ARN: arn:aws:kms:us-east-1:533595510771:alias/smart-parking-dev-invoices
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/payment-service
      tag: b2e12ad3366c82738566518639d2977be0bd2424
schedulerService:
  deployment:
    replicas: 1
    image:
      repository: 533595510771.dkr.ecr.us-east-1.amazonaws.com/scheduler-service
      tag: 91e855f81277ba612f6e6ce0f67ce2fbf5fb34aa
ingress:
  name: smart-parking-dev-alb
