apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-argo-rollouts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: smart-parking
  revisionHistoryLimit: 5
  source:
    repoURL: https://github.com/argoproj/argo-rollouts.git
    targetRevision: stable
    path: manifests
    directory:
      include: "install.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
