apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: smart-parking
  revisionHistoryLimit: 5
  source:
    repoURL: https://github.com/UST-Capstone-Project/Parking-System.git
    targetRevision: dev
    path: eks-deployment/helm
    helm:
      releaseName: smart-parking-dev
      valueFiles:
        - values/argocd-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
