apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: smart-parking
  revisionHistoryLimit: 5
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 87.2.1
    helm:
      releaseName: monitoring
      values: |
        grafana:
          grafana.ini:
            server:
              root_url: "%(protocol)s://%(domain)s/grafana/"
              serve_from_sub_path: true
          ingress:
            enabled: true
            ingressClassName: alb
            annotations:
              alb.ingress.kubernetes.io/group.name: smart-parking-prod-edge
              alb.ingress.kubernetes.io/group.order: "16"
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/healthcheck-path: /grafana/api/health
              alb.ingress.kubernetes.io/success-codes: "200-399"
            path: /grafana
            pathType: Prefix
        prometheus:
          ingress:
            enabled: true
            ingressClassName: alb
            annotations:
              alb.ingress.kubernetes.io/group.name: smart-parking-prod-edge
              alb.ingress.kubernetes.io/group.order: "17"
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/healthcheck-path: /promethous/-/healthy
              alb.ingress.kubernetes.io/success-codes: "200-399"
            paths:
              - /promethous
            pathType: Prefix
          prometheusSpec:
            externalUrl: /promethous
            routePrefix: /promethous
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
        alertmanager:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
