apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  server.insecure: "true"
  server.rootpath: /argocd
  server.basehref: /argocd
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-edge
  namespace: argocd
  annotations:
    alb.ingress.kubernetes.io/group.name: smart-parking-prod-edge
    alb.ingress.kubernetes.io/group.order: "10"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /argocd
    alb.ingress.kubernetes.io/success-codes: "200-399"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /argocd
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
